### ISSUE TITLE
Cedarview version

### ISSUE THREAD

**Issue by ghost** [th0ma7/synology#1]
Hi
Is any chance to you compile for me and your repo Tvheadend for platform Cedarview ? I need file spk please....

**Comment by th0ma7** [comment]
Source for issues related to spksrc is https://github.com/SynoCommunity/spksrc
Duplicate of https://github.com/SynoCommunity/spksrc/issues/3863

**Comment by ghost** [comment]
But it is old version... but i want version 4.3
