### ISSUE TITLE
DVB drivers for DSM7

### ISSUE THREAD

**Issue by tcamargo** [th0ma7/synology#12]
Hi Vincent, 

Did you manage to compile media_build for DSM7?

Thanks!

**Comment by th0ma7** [comment]
Nope, not yet and haven`t even tried.
Synology hasn't yet published any kernel sources for DSM7 so there is basically nothing we can do.

**Comment by boardlord1** [comment]
Hi, it seems Synology did publish the kernel sources for DSM7.
https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.0-41890
