### ISSUE TITLE
/usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jesus2099** [th0ma7/synology#15]
Since version 4.4.2-43 on DSM 6, I have this error message:

> `/usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

I cannot run `/usr/local/ffmpeg/bin/ffmpeg` any more.

**Comment by th0ma7** [comment]
Please ensure to use the official SynoCommunity released package.  Package provided in here are only for beta testing prior to official release.  If issue still exists then open up an issue on https://github.com/SynoCommunity/spksrc

**Comment by jesus2099** [comment]
Thank you, I will open the ticket over there.
I do use the SynoCommunity package.
I came here because it's the link I found in the package about page.

**Comment by th0ma7** [comment]
Thnx for the info, indeed I just noticed that (e.g. about page).
