### ISSUE TITLE
extended support for more devices

### ISSUE THREAD

**Issue by micenusa** [th0ma7/synology#16]
Hi,
sorry for bothering you!
Is there any way to have these TV tuner drivers working for DSM 7.X and more tuners and Synology NAS-es?
Thanks in advance!

**Comment by th0ma7** [comment]
I am currently working (when my cycles allows it) on a PR to release a set of USB tuners for Synology 6.x and 7.0 (as 7.1 kernel wasn't released yet).  But there are many blockers and this will take a while.

I invite you to follow this pull request if you want to learn more: https://github.com/SynoCommunity/spksrc/pull/5253
