### ISSUE TITLE
Dsm 7 and WinTV-dualHD 01590

### ISSUE THREAD

**Issue by mapoloco** [th0ma7/synology#18]
Hi, i have try to make the same as you did with yours but I am very lost.  Can you help me to compile them?

I know you can put new drivers because I used Jadahl drivers to get tty.

I have drivers for WinTV-dualHD 01590: https://www.linuxtv.org/wiki/index.php/Hauppauge_WinTV-dualHD#Drivers
Xpenology 7.1 update3 3615xs
Microserver HP gen8

I am in your hands. Thank you very much.

**Comment by dnmnhat** [comment]
Same case @mapoloco 
I also tried to do the same as you but failed.
Can you help me to compile them?
I have USB DVB Geniatech T230C : https://www.linuxtv.org/wiki/index.php/Geniatech_T230C
Xpenology 7.1.0-42661 update 4 DS920+ ( geminilake - build by redpill loader )
Main : Intel Celeron J1900

**Comment by th0ma7** [comment]
It's actually next on my todo list.  I'll be returning on this in the next few weeks but that takes time.  My hope is to solve the few build issues I have against DSM7 kernels.  Also note Synology hasn't released kernels for DSM 7.1 so kernel modules for DSM 7.0 may or may not work on that.

You can follow-up my work here: https://github.com/SynoCommunity/spksrc/pull/5253

**Comment by mapoloco** [comment]
> It's actually next on my todo list. I'll be returning on this in the next few weeks but that takes time. My hope is to solve the few build issues I have against DSM7 kernels. Also note Synology hasn't released kernels for DSM 7.1 so kernel modules for DSM 7.0 may or may not work on that.
> 
> You can follow-up my work here: [SynoCommunity/spksrc#5253](https://github.com/SynoCommunity/spksrc/pull/5253)

Xpenology 7.1 update4 3622xs
Microserver HP gen8

I have installed [jadahl ](http://www.jadahl.com/iperf-arp-scan/DSM_7.0/broadwellnk/) drivers to get my zigbee drivers and they work. Only I musted to load those items at synology start as root.

sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/cp210x.ko
sudo insmod /lib/modules/ch341.ko
sudo /sbin/modprobe usbserial
sudo /sbin/modprobe ftdi_sio
sudo /sbin/modprobe cdc-acm
sudo chmod 666 /dev/ttyACM*
sudo chmod 666 /dev/ttyUSB*

Maybe it helps you. Thank yoy very much.

**Comment by dnmnhat** [comment]
there is still no new information for DSM 7.1.1 to use USB DVB with TVHeadend right everyone???

**Comment by mapoloco** [comment]
nope :( still waiting...

**Comment by dnmnhat** [comment]
me too :(

**Comment by belgio99** [comment]
I managed to make the dualHD (and possibly other devices?) work with DSM 7. 

I'm currently using it flawlessly with DSM 7.2.1 and Plex. Unless you're using Geminilake as I am, you'll have to compile the drivers yourself, but what I wrote may help you on how to do it.
Details and guide at https://github.com/belgio99/dsm7-dvb-drivers
(My repo gives a general idea on how I did it: depending on your architecture and CPU family, your mileage may vary).

**Comment by th0ma7** [comment]
awesome work @belgio99

For other on the thread, on my end I've been trying to build the entire media tree against all synology kernels but this has proven to be quite challenging and could not find enough cycles to pursue over the last year.  Still on my todo but that list is growing with ever more items than I can handle.  Hopefully I'll return to it before long.

**Comment by mateusz880** [comment]
Hi,

After uploading the files to Synology DS220+ according to the instructions.
I get something like this after executing the dmesg command.

> 
[   94.733872] mc: module verification failed: signature and/or required key missing - tainting kernel
[   94.744731] mc: Linux media interface: v0.10
[   94.766301] WARNING: You are using an experimental version of the media stack.
                As the driver is backported to an older kernel, it doesn't offer
                enough quality for its usage in production.
                Use it with care.
               Latest git patches (needed if you report a bug to linux-media@vger.kernel.org):
                340ce50f75a6bdfe6d1850ca49ef37a8e2765dd1 media: hantro: Enable HOLD_CAPTURE_BUF for H.264
                11442b7c937544dcb2e3525b17dc8f3425e8d9a2 media: hantro: Add H.264 field decoding support
                3630e4933d40af53f698555d88e6143dc2d140b3 media: hantro: h264: Make dpb entry management more robust
[   94.916611] videodev: Linux video capture interface: v2.00
[   94.922733] WARNING: You are using an experimental version of the media stack.
                As the driver is backported to an older kernel, it doesn't offer
                enough quality for its usage in production.
                Use it with care.
               Latest git patches (needed if you report a bug to linux-media@vger.kernel.org):
                340ce50f75a6bdfe6d1850ca49ef37a8e2765dd1 media: hantro: Enable HOLD_CAPTURE_BUF for H.264
                11442b7c937544dcb2e3525b17dc8f3425e8d9a2 media: hantro: Add H.264 field decoding support
                3630e4933d40af53f698555d88e6143dc2d140b3 media: hantro: h264: Make dpb entry management more robust
[   96.606525] WARNING: You are using an experimental version of the media stack.
                As the driver is backported to an older kernel, it doesn't offer
                enough quality for its usage in production.
                Use it with care.
               Latest git patches (needed if you report a bug to linux-media@vger.kernel.org):
                340ce50f75a6bdfe6d1850ca49ef37a8e2765dd1 media: hantro: Enable HOLD_CAPTURE_BUF for H.264
                11442b7c937544dcb2e3525b17dc8f3425e8d9a2 media: hantro: Add H.264 field decoding support
                3630e4933d40af53f698555d88e6143dc2d140b3 media: hantro: h264: Make dpb entry management more robust
[   96.922181] usbcore: registered new interface driver em28xx
[   96.955168] em28xx: Registered (Em28xx dvb Extension) extension

**Comment by 888Mouse** [comment]
Hi, I am Korean. I want to work with you Please send me a message on my Telegram @z7777_88

**Comment by micenusa** [comment]
hi, any news with the compiled kernel modules?
I tried also @belgio99 geminilake approach with no success!
I succed also to load his compiled drivers on my geminilake, but they are not anough for my hardware (xbox tv tuners)..
I tried several times with no success....

**Comment by th0ma7** [comment]
Feel free to continue exchanging in here but this howto doesn`t apply anymore.  The spksrc framework was modified to allow building kernel modules but I don't have the need nor the cycles to complete the work on including the linux-media tree to build backported kernel modules.
