### ISSUE TITLE
Tune Help

### ISSUE THREAD

**Issue by jltnol** [th0ma7/synology#19]
So I've got a Synology DS that I'd like to use to record some OTA TV shows... but the USB tuners you have listed I'm not able to find on the Hauppauge website.  I'll ask full in the knowledge it's impossible for you to know compatibly with hardware you don't have access to, but what's your best guess about the Hauppauge 1595 WinTV-dualHD and the TVheadend package for Synology?

**Comment by th0ma7** [comment]
Honestly, I strongly suggest you to purchase a HDHomeRun which works like a charm with tvheadend.  I'm actually about to release a new tvheadend version which support the latest update of HDHomeRun allowing you to use it as an IPTV device natively which is great and simplifies configuration a lot.

As for WinTV-dualHD, I actually own one and I'm not using nor maintaining the driver for it.

**Comment by jltnol** [comment]
Thank you ever so much for taking the time to respond. I’ll look at the HomeRun device for this project.JTOn Nov 19, 2022, at 7:35 AM, Vincent Fortier ***@***.***> wrote:﻿
Honestly, I strongly suggest you to purchase a HDHomeRun which works like a charm with tvheadend.  I'm actually about to release a new tvheadend version which support the latest update of HDHomeRun allowing you to use it as an IPTV device natively which is great and simplifies configuration a lot.
As for WinTV-dualHD, I actually own one and I'm not using nor maintaining the driver for it.
