### ISSUE TITLE
synology package always gives 403 forbidden page

### ISSUE THREAD

**Issue by awayand** [th0ma7/synology#2]
after entering the wizard, and hitting "save", I get "wizard access denied", then after refresh a 403 page. Even installing the stable or beta version. how do I clear out the package completely to do a reinstall?

 synology/packages/tvheadend_x64-6.1_4.3.20191128~221c29b-19.spk

**Comment by th0ma7** [comment]
This is a really odd behaviour that I never saw.
`tvheadend` package requires `ffmpeg`: are both currently installed?

**Comment by Laibalion** [comment]
@awayand, As I've recently installed it myself on my Synology without issues, it's weird that it wouldn't work for you.
Which model of DS do you use and which version of DSM is it running?
I've installed tvheadend_apollolake-6.1_4.3.20191128~221c29b-19.spk, as my model has an ApolloLake cpu inside.

**Comment by th0ma7** [comment]
closed due to no feedbacks.
