### ISSUE TITLE
DSM 6.2.3-25426 ffmpeg 4.2.2-28 and 4.2.2-30 doesn't works for encode sound

### ISSUE THREAD

**Issue by Cadkey** [th0ma7/synology#3]
for exemple
`ffmpeg -i "$i" -map 0 -c copy -c:a:0 eac3 -b:a 960k "$out"`
his line was working 3 days ago.
following the update of DSM, the output file no longer has a soundtrack.

**Comment by th0ma7** [comment]
Hi @Cadkey , having a sample I could work with to try it out?
Also, have you tried changing the audio type? To determine if it's purely `eac3` related.

**Comment by Cadkey** [comment]
Bonjour,Je suppose que vous êtes français.En fait votre paquet sur synocommunity fonctionne très bien. J'utilise votre ffmpeg en ligne de commande pour encoder des flux des dans des mkv en eac3. La toute dernière mise à jour DSM m'avait cassé des modifications trouvées sur Ghitub. Avec find j'ai trouvé où était installé votre ffmpeg et je l'utilise en ligne de commande parce que celui de Synology est bridé. Je n'utilise pas vidéo station mais Plex.Du coup le problème m'a obligé à réfléchir. Très content de votre paquet, j'ai une solution pérenne.Merci beaucoup.

**Comment by th0ma7** [comment]
Bonjour @Cadkey ,
donc si je comprends bien l'enjeu est réglé?  et n'était en fait que l'utilisation du mauvais binaire de ffmpeg?  (défaut système Synology vs `/var/packages/ffmpeg/target/bin/ffmpeg`)

**Comment by Cadkey** [comment]
Bonjour,Oui exactement.Je ne savais pas qu'il y avait plusieurs ffmpeg sur le Synology, surveillance Station, vidéo station, etc
