### ISSUE TITLE
ffmpeg pour Geminilake

### ISSUE THREAD

**Issue by Cadkey** [th0ma7/synology#4]
Bonjour
Avez-vous un package pour le 920+, geminilake?
Merci
cette version fonctionne ffmpeg_x64-6.1_4.2.3-30.spk
MErci

**Comment by th0ma7** [comment]
Effectivment la version `x64` devrait fonctionner pour `geminilake`.

**Comment by Cadkey** [comment]
Oui, j'ai testé. Les deux fonctionnent, 4.2.4 et 4.3.1
Elles ne sont pas signées mais ça passe très bien sur DS920+ donc aussi sur 720+ et 420+
Merci beaucoup
