### ISSUE TITLE
Username / password - spk Synocommunity

### ISSUE THREAD

**Issue by rodnheli** [th0ma7/synology#6]
Hi,
sorry for probably stupid question - installed you tvheadend spk package from synocommunity - v4.3.20201011~9ed76c0-26 - on DSM 920  version 6.2.3-25426 Update 2.

Installation without problems - but with which credentials can I login? Searched the web, your WIki and tried some default credentials... without luck...

Thank you very much for your help!

**Comment by th0ma7** [comment]
The default credentials are admin/admin.
Sorry for taking so long to answer.
