### ISSUE TITLE
Synology 7 issues

### ISSUE THREAD

**Issue by martin4eel** [th0ma7/synology#7]
Hello, 

I am pretty sure you know and are working on privilige settings for ffmpeg for syno 7. 

I was stupid and upgraded and now I cant install ffmpeg due to it needing root access.

**Comment by mitchoklemen** [comment]
...like me... and now I'm sorry I can't use Tvheadend on daily basis.

**Comment by Laibalion** [comment]
I don't mean to detract from @th0ma7 's work on this package in any form, but this is one of the reasons I switched to tvheadend docker container on my Synology NAS. I had to many issues with root access (mainly for installing and configuring my xmltv grabber), and needing to reinstall/reconfigure the grabber on every OS or package update.
The LinuxServer tvheadend docker image seems to be working well and seemingly no issues with ffmpeg encoding.

**Comment by th0ma7** [comment]
Sorry as this issue didn't got much attention out of me.  I normally follow bug entries on https://github.com/SynoCommunity/spksrc where my work ends-up being published.

There are experimental packages available in https://github.com/th0ma7/synology/tree/master/packages
Feel free to use and test.

As for @Laibalion, the key difference are two things:
1. hardware acceleration: using docker you don't have access to GPU decoding with ffmpeg
2. i'm also pursuing the ability to load linuxtv USB DVB modules on Synology.

Both requirements can somewhat be circumvented with docker but not easily.  As for hardware decoding, it is only really available on "recent" Intel arches as such some may not bother at all with it.

To me docker tvheadend really is ideal for hdhomerun TCP-IP usages or NAS that don't have GPU hardware decoding.  So each has its own "niche" I guess.
